version: '2'
services:
  web:
    image: selecao_test:latest
    build: .
    command: bash -c "pip install -r /app/requirements.txt > .log-requirements.txt && echo '>>>>> STARTING' && python manage.py runserver 0.0.0.0:8000"
    ports:
        - "8000:8000"
    volumes:
      - .:/app